spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/nkso-access-helper
  application:
    name: ms-access-helper-manager-app
  datasource:
    url: jdbc:ucanaccess://M:/project/db/bd_nkso.accdb;memory=false
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    username:
    password:
    hikari:
      auto-commit: true
      max-lifetime: 30000
      leak-detection-threshold: 10000
  jpa:
    hibernate:
      globally_quoted_identifiers: false
      auto_quote_keyword: false
      ddl-auto: none
    show-sql: true
    database-platform: io.github.mrergos.dialect.MSAccessBracketDialect
    properties:
#      jakarta.persistence.metamodel.helper.enabled: false
#      hibernate.hbm2ddl.auto: none # Уже установлено, но на всякий случай
#      hibernate.metadata.extractors.delegate: false # Отключает извлечение метаданных
      hibernate.globally_quoted_identifiers: false
      hibernate.auto_quote_keyword: false
      hibernate:
#        packagesToScan: io.github.mrergos.entity
        dialect: io.github.mrergos.dialect.MSAccessBracketDialect
page.size: 10
server:
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace
      engine:
        jdbc:
          spi:
            SqlExceptionHelper: error